### PR TITLE
[MM-60613] Add Desktop App Metrics dashboard

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
This is the initial PR for the Desktop App metrics dashboard, currently just measuring CPU and memory usage.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-60613

### CODE REVIEW

**Review by larkox — APPROVED** [review]

**Comment by larkox** [comment]
Let me know when you want this on grafana.com

**Comment by agnivade** [comment]
Just a couple of questions here:
- I see that the labels are platform and version. So this would probably help us to track down performance regressions by version, which would be a great start. But the user's environment also constantly changes. So if a user has a new (and more powerful) laptop when they use a newer app version, this would mask any regression.
- It would be good to add thresholds to each panel so that customers know what is good and what is bad.
- We should have a clear set of "actionable" steps to identify a regression and act on it.

cc @lieut-data for any comments.

**Comment by devinbinnie** [comment]
> * I see that the labels are platform and version. So this would probably help us to track down performance regressions by version, which would be a great start. But the user's environment also constantly changes. So if a user has a new (and more powerful) laptop when they use a newer app version, this would mask any regression.

This would only be the case if they were to switch operating environments as well though, which for Desktop App might change the behaviour of the app a fair bit. If we're looking for regression in the app in general, we can just filter by All and see everything, which for issues with our code will be likely what we're looking for.

> * It would be good to add thresholds to each panel so that customers know what is good and what is bad.

You're right, but unfortunately I don't fully know yet what is good or bad for the average user. I can say on my personal machine that using 1-2% seems reasonable, but I'm not sure if that's true across the board. It also depends on what the user is actually doing at the time.

I want to get a better picture with more users submitting data before I make a decision of what's a good number. Similar to how I did with notifications.

> * We should have a clear set of "actionable" steps to identify a regression and act on it.

This I am working on for support - so they can at least rule out variables that aren't us. Would you say those steps live here? I'd think they should live somewhere - maybe Confluence or something.

**Comment by agnivade** [comment]
> Would you say those steps live here? I'd think they should live somewhere - maybe Confluence or something.

Confluence works!

> I want to get a better picture with more users submitting data before I make a decision of what's a good number. Similar to how I did with notifications.

Lovely

**Review by agnivade — APPROVED** [review]

**Comment by devinbinnie** [comment]
@larkox Good to publish when you're ready :)

**Pull request merged**
